### ISSUE TITLE
Other websites

### ISSUE THREAD

**Issue by hard-tek** [pystardust/waldl#7]
Hello,
can this be used for other websites? For example adult websites with pictures, something like _pornpics.com_ or similar.
Thanks.

**Comment by pystardust** [comment]
This is wallhaven specific, but if the other site has an api then it would be possible to make a new script for it. If it doesn't have an api then we would need to scrape it.
Implementing a new site would need most of the code to be changed so id say its better off in a new project

**Comment by hard-tek** [comment]
@pystardust agree. 

Looking forward for new projects.
