### ISSUE TITLE
Save wallpapers to directory named based on $query?

### ISSUE THREAD

**Issue by hamensman** [pystardust/waldl#9]
Not an issue per se, but curious about something.

All wallpapers, not matter what you search, are saved to .`local/share/wallhaven`. But what if I search for, say, `batman` and I want the wallpapers to be saved to `.local/share/wallhaven/batman`? Or if I search for `pokemon`, have the wallpapers saved to `.local/share/wallhaven/pokemon`. And so on...

`walldir="$HOME/.local/share/wallhaven/$query"` can't be done, because $query is not defined yet. How could the above be achieved instead?

And with search for query with spaces is allowed, how would I have spaces and special characters (slash, apostrophe, colon, etc.) converted to underscore?

E.g., search final fantasy, saved to final_fantasy. Search fate/stay night, saved to fate_stay_night.

**Comment by NoRMaNxLLy** [comment]
this could by done by adding this line after the line 157:
walldir="$walldir/${query//[^[:alnum:]]/_}" 
mkdir -p $walldir

by the way, this didn't work at first time, took me 30m to find out that the shebang is /bin/sh,
and mine is linked to dash, which didnot support this substitution.

**Comment by hamensman** [comment]
> walldir="$walldir/${query//[^[:alnum:]]/_}"

Thank you for the tip.
I found if I add that line in the `start up commands` section like this...
```bash
rm -rf "$cachedir"
walldir="$walldir/${query//[^[:alnum:]]/_}"
mkdir -p "$walldir" "$cachedir"
```
...it creates the desired effect.

**Comment by hamensman** [comment]
```bash
rm -rf "$cachedir"
walldir="$walldir/${query//[^[:alnum:]]/_}"
mkdir -p "$walldir" "$cachedir"
```
Works on my Arch setup fine. But when trying it on my Debian setup, nothing appears when I type in a name.

So I opened `waldl` it in the terminal and typed in a name to see if I get any kind of output. And I got this: `/usr/local/bin/waldl: 54: Bad substitution`

Does anyone know what this means, and why this is happening on my Debian setup, but not on my Arch?

**Comment by NoRMaNxLLy** [comment]
> ```shell
> rm -rf "$cachedir"
> walldir="$walldir/${query//[^[:alnum:]]/_}"
> mkdir -p "$walldir" "$cachedir"
> ```
> 
> Works on my Arch setup fine. But when trying it on my Debian setup, nothing appears when I type in a name.
> 
> So I opened `waldl` it in the terminal and typed in a name to see if I get any kind of output. And I got this: `/usr/local/bin/waldl: 54: Bad substitution`
> 
> Does anyone know what this means, and why this is happening on my Debian setup, but not on my Arch?

that's what i tried to explain above.
by default, in debian /bin/sh is link to the dash shell, and dash shell does not support this kind of substitiution: ${var//search/replace}.
so you might change your default shell, and link it to /bin/bash, or simply just change the shebang of the script itself.

**Comment by hamensman** [comment]
I see!

Thanks. I changed the shebang to `#!/bin/bash`, which works fines now!
